package entities;
// Generated 5 mars 2018 15:45:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Auth generated by hbm2java
 */
public class Auth  implements java.io.Serializable {


     private Integer id;
     private String password;
     private Set<User> users = new HashSet<User>(0);

    public Auth() {
    }

    public Auth(String password, Set<User> users) {
       this.password = password;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


