package entities;
// Generated 5 mars 2018 15:45:52 by Hibernate Tools 4.3.1



/**
 * Linestock generated by hbm2java
 */
public class Linestock  implements java.io.Serializable {


     private Integer id;
     private Item item;
     private Stockorder stockorder;
     private Integer quantity;
     private Integer price;

    public Linestock() {
    }

	
    public Linestock(Item item, Stockorder stockorder) {
        this.item = item;
        this.stockorder = stockorder;
    }
    public Linestock(Item item, Stockorder stockorder, Integer quantity, Integer price) {
       this.item = item;
       this.stockorder = stockorder;
       this.quantity = quantity;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Stockorder getStockorder() {
        return this.stockorder;
    }
    
    public void setStockorder(Stockorder stockorder) {
        this.stockorder = stockorder;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }




}


