package entities;
// Generated 5 mars 2018 15:45:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer id;
     private Address address;
     private Shippinginfo shippinginfo;
     private User user;
     private String date;
     private String status;
     private String tag;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);
     private Set<Lineorder> lineorders = new HashSet<Lineorder>(0);

    public Orders() {
    }

	
    public Orders(Address address, Shippinginfo shippinginfo, User user) {
        this.address = address;
        this.shippinginfo = shippinginfo;
        this.user = user;
    }
    public Orders(Address address, Shippinginfo shippinginfo, User user, String date, String status, String tag, Set<Transaction> transactions, Set<Lineorder> lineorders) {
       this.address = address;
       this.shippinginfo = shippinginfo;
       this.user = user;
       this.date = date;
       this.status = status;
       this.tag = tag;
       this.transactions = transactions;
       this.lineorders = lineorders;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public Shippinginfo getShippinginfo() {
        return this.shippinginfo;
    }
    
    public void setShippinginfo(Shippinginfo shippinginfo) {
        this.shippinginfo = shippinginfo;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }
    public Set<Lineorder> getLineorders() {
        return this.lineorders;
    }
    
    public void setLineorders(Set<Lineorder> lineorders) {
        this.lineorders = lineorders;
    }




}


