package entities;
// Generated 5 mars 2018 15:45:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private Auth auth;
     private String name;
     private String firstName;
     private String mail;
     private String signupDate;
     private Boolean deleted;
     private String role;
     private String tag;
     private Set<Session> sessions = new HashSet<Session>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<Transaction> transactions = new HashSet<Transaction>(0);
     private Set<Orders> orderses = new HashSet<Orders>(0);
     private Set<Linecart> linecarts = new HashSet<Linecart>(0);
     private Set<Rating> ratings = new HashSet<Rating>(0);
     private Set<Stockorder> stockorders = new HashSet<Stockorder>(0);
     private Set<Address> addresses = new HashSet<Address>(0);

    public User() {
    }

	
    public User(String role) {
        this.role = role;
    }
    public User(Auth auth, String name, String firstName, String mail, String signupDate, Boolean deleted, String role, String tag, Set<Session> sessions, Set<Comment> comments, Set<Transaction> transactions, Set<Orders> orderses, Set<Linecart> linecarts, Set<Rating> ratings, Set<Stockorder> stockorders, Set<Address> addresses) {
       this.auth = auth;
       this.name = name;
       this.firstName = firstName;
       this.mail = mail;
       this.signupDate = signupDate;
       this.deleted = deleted;
       this.role = role;
       this.tag = tag;
       this.sessions = sessions;
       this.comments = comments;
       this.transactions = transactions;
       this.orderses = orderses;
       this.linecarts = linecarts;
       this.ratings = ratings;
       this.stockorders = stockorders;
       this.addresses = addresses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Auth getAuth() {
        return this.auth;
    }
    
    public void setAuth(Auth auth) {
        this.auth = auth;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getSignupDate() {
        return this.signupDate;
    }
    
    public void setSignupDate(String signupDate) {
        this.signupDate = signupDate;
    }
    public Boolean getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }
    public Set<Session> getSessions() {
        return this.sessions;
    }
    
    public void setSessions(Set<Session> sessions) {
        this.sessions = sessions;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }
    public Set<Linecart> getLinecarts() {
        return this.linecarts;
    }
    
    public void setLinecarts(Set<Linecart> linecarts) {
        this.linecarts = linecarts;
    }
    public Set<Rating> getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set<Rating> ratings) {
        this.ratings = ratings;
    }
    public Set<Stockorder> getStockorders() {
        return this.stockorders;
    }
    
    public void setStockorders(Set<Stockorder> stockorders) {
        this.stockorders = stockorders;
    }
    public Set<Address> getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }




}


